/**
 * Tests for ClaudeAdapter
 */

import { describe, it, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { ClaudeAdapter } from '../../src/adapters/claude-adapter.js';
import type { AreteConfig } from '../../src/models/workspace.js';

describe('ClaudeAdapter', () => {
  let adapter: ClaudeAdapter;

  beforeEach(() => {
    adapter = new ClaudeAdapter();
  });

  describe('generateRootFiles', () => {
    const mockConfig: AreteConfig = {
      version: '1.0.0',
      source: 'npm',
      agent_mode: 'guide',
      created: '2026-02-23',
      ide_target: 'claude',
    };

    it('generates CLAUDE.md file (not AGENTS.md)', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      assert.ok('CLAUDE.md' in files, 'Should generate CLAUDE.md');
      assert.ok(!('AGENTS.md' in files), 'Should NOT generate AGENTS.md');
    });

    it('CLAUDE.md contains CLI section', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const claudeMd = files['CLAUDE.md'];
      
      // The comprehensive dist/AGENTS.md (transformed) has [CLI] section
      assert.ok(
        claudeMd.includes('[CLI]') || claudeMd.includes('## CLI'),
        'Should contain CLI section'
      );
    });

    it('CLAUDE.md contains Skills section', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const claudeMd = files['CLAUDE.md'];
      
      // The comprehensive dist/AGENTS.md (transformed) has [Skills] section
      assert.ok(
        claudeMd.includes('[Skills]') || claudeMd.includes('## Skills'),
        'Should contain Skills section'
      );
    });

    it('CLAUDE.md contains Intelligence section for guide mode', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const claudeMd = files['CLAUDE.md'];
      
      // The comprehensive dist/AGENTS.md (transformed) has [Intelligence] section
      assert.ok(
        claudeMd.includes('[Intelligence]') || claudeMd.includes('## Intelligence'),
        'Should contain Intelligence section'
      );
    });

    it('CLAUDE.md contains version footer', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const claudeMd = files['CLAUDE.md'];
      
      assert.ok(claudeMd.includes('## Version'), 'Should contain Version section');
      assert.ok(claudeMd.includes('v1.0.0'), 'Should contain version number');
      assert.ok(claudeMd.includes('Generated by Areté'), 'Should contain generation note');
    });

    it('CLAUDE.md transforms .cursor paths to .claude paths', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const claudeMd = files['CLAUDE.md'];
      
      // Should NOT contain .cursor/ paths (except possibly in comments about BUILD vs USER)
      // The main content should use .claude/ paths
      const lines = claudeMd.split('\n').filter(line => 
        !line.includes('BUILD') && 
        !line.includes('build:') &&
        !line.includes('<!-- ') &&
        line.includes('.cursor/')
      );
      assert.equal(lines.length, 0, 'Should not have .cursor/ paths in main content');
    });

    it('CLAUDE.md contains arete route command', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const claudeMd = files['CLAUDE.md'];
      
      assert.ok(claudeMd.includes('arete route'), 'Should contain arete route command');
    });

    it('has basic structure in output', () => {
      // Verifies the output has basic structure (from dist/AGENTS.md or fallback)
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const claudeMd = files['CLAUDE.md'];
      
      // Should have basic structure regardless of source
      assert.ok(claudeMd.includes('Areté'), 'Should contain Areté title');
      // The comprehensive version uses [Workspace] compressed format
      assert.ok(
        claudeMd.includes('[Workspace]') || claudeMd.includes('Workspace'),
        'Should contain workspace info'
      );
    });
  });

  describe('IDE configuration', () => {
    it('has correct target', () => {
      assert.equal(adapter.target, 'claude');
    });

    it('has correct config directory', () => {
      assert.equal(adapter.configDirName, '.claude');
    });

    it('has correct rule extension', () => {
      assert.equal(adapter.ruleExtension, '.md');
    });
  });

  describe('transformRuleContent', () => {
    it('transforms .cursor/ to .claude/', () => {
      const input = 'Read .cursor/rules/file.mdc for guidance.';
      const output = adapter.transformRuleContent(input);
      assert.equal(output, 'Read .claude/rules/file.md for guidance.');
    });

    it('transforms .cursor/skills/ to .agents/skills/', () => {
      const input = 'Load .cursor/skills/meeting-prep/SKILL.md';
      const output = adapter.transformRuleContent(input);
      assert.equal(output, 'Load .agents/skills/meeting-prep/SKILL.md');
    });
  });
});
