/**
 * Tests for CursorAdapter
 */

import { describe, it, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { CursorAdapter } from '../../src/adapters/cursor-adapter.js';
import type { AreteConfig } from '../../src/models/workspace.js';

describe('CursorAdapter', () => {
  let adapter: CursorAdapter;

  beforeEach(() => {
    adapter = new CursorAdapter();
  });

  describe('generateRootFiles', () => {
    const mockConfig: AreteConfig = {
      version: '1.0.0',
      source: 'npm',
      agent_mode: 'guide',
      created: '2026-02-23',
      ide_target: 'cursor',
    };

    it('generates AGENTS.md file', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      assert.ok('AGENTS.md' in files, 'Should generate AGENTS.md');
    });

    it('AGENTS.md contains CLI section', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const agentsMd = files['AGENTS.md'];
      
      // The comprehensive dist/AGENTS.md has [CLI] section with pipe-delimited commands
      assert.ok(
        agentsMd.includes('[CLI]') || agentsMd.includes('## CLI'),
        'Should contain CLI section'
      );
    });

    it('AGENTS.md contains Skills section', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const agentsMd = files['AGENTS.md'];
      
      // The comprehensive dist/AGENTS.md has [Skills] section
      assert.ok(
        agentsMd.includes('[Skills]') || agentsMd.includes('## Skills'),
        'Should contain Skills section'
      );
    });

    it('AGENTS.md contains Intelligence section for guide mode', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const agentsMd = files['AGENTS.md'];
      
      // The comprehensive dist/AGENTS.md has [Intelligence] section
      assert.ok(
        agentsMd.includes('[Intelligence]') || agentsMd.includes('## Intelligence'),
        'Should contain Intelligence section'
      );
    });

    it('AGENTS.md contains version footer', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const agentsMd = files['AGENTS.md'];
      
      assert.ok(agentsMd.includes('## Version'), 'Should contain Version section');
      assert.ok(agentsMd.includes('v1.0.0'), 'Should contain version number');
      assert.ok(agentsMd.includes('Generated by Areté'), 'Should contain generation note');
    });

    it('AGENTS.md contains arete route command', () => {
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const agentsMd = files['AGENTS.md'];
      
      assert.ok(agentsMd.includes('arete route'), 'Should contain arete route command');
    });

    it('has basic structure in output', () => {
      // Verifies the output has basic structure (from dist/AGENTS.md or fallback)
      const files = adapter.generateRootFiles(mockConfig, '/workspace');
      const agentsMd = files['AGENTS.md'];
      
      // Should have basic structure regardless of source
      assert.ok(agentsMd.includes('Areté'), 'Should contain Areté title');
      // The comprehensive version uses [Workspace] compressed format
      assert.ok(
        agentsMd.includes('[Workspace]') || agentsMd.includes('Workspace'),
        'Should contain workspace info'
      );
    });
  });

  describe('IDE configuration', () => {
    it('has correct target', () => {
      assert.equal(adapter.target, 'cursor');
    });

    it('has correct config directory', () => {
      assert.equal(adapter.configDirName, '.cursor');
    });

    it('has correct rule extension', () => {
      assert.equal(adapter.ruleExtension, '.mdc');
    });
  });
});
