/**
 * Generates CLAUDE.md content for Arete PM workspaces.
 *
 * Pure function — no I/O, no side effects.
 */

import type { AreteConfig } from '../models/workspace.js';
import type { SkillDefinition } from '../models/skills.js';

/**
 * Generate the full CLAUDE.md content for an Arete workspace.
 */
export function generateClaudeMd(
  config: AreteConfig,
  skills: SkillDefinition[]
): string {
  const sections = [
    generateIdentity(),
    generateWorkspaceStructure(),
    generateSlashCommands(skills),
    generateIntelligenceServices(),
    generateMemory(),
    generateWorkingPatterns(),
    generateFooter(config),
  ];

  return sections.join('\n\n') + '\n';
}

function generateIdentity(): string {
  return `# Arete PM Workspace

This is an Arete PM workspace. Arete (arete) means excellence — helping product builders
gain clarity, navigate ambiguity, and move faster.

You are a senior product partner embedded in a PM's daily workflow. You have access to
workspace context (goals, projects, people, meetings) and intelligence services that
let you search, brief, and resolve references across the workspace.

When a user asks for help, check if a slash command matches before doing ad-hoc work.`;
}

function generateWorkspaceStructure(): string {
  return `## Workspace Structure

\`\`\`
now/                  Current focus: week.md, today.md, scratchpad.md, agendas/
goals/                Strategy: strategy.md, quarter goals
context/              Business context — source of truth
projects/             active/, archive/
people/               internal/, customers/, users/
resources/            meetings/, notes/
.arete/               memory/items/, memory/summaries/
.agents/              skills/, profiles/
templates/            Workspace templates
\`\`\``;
}

function generateSlashCommands(skills: SkillDefinition[]): string {
  const lines: string[] = [
    '## Slash Commands',
    '',
    '| Command | Description |',
    '|---------|-------------|',
  ];

  for (const skill of skills) {
    const desc = (skill.description || skill.name).replace(/\|/g, '\\|');
    lines.push(`| /${skill.id} | ${desc} |`);
  }

  lines.push('');
  lines.push(
    'For ambiguous requests not matching a command, use `arete skill route "<message>"` to find the right skill.'
  );

  return lines.join('\n');
}

function generateIntelligenceServices(): string {
  return `## Intelligence Services

Search, briefing, and resolution commands available via the \`arete\` CLI:

\`\`\`bash
# Search across workspace (scopes: memory, meetings, context, projects, people)
arete search "query"

# Temporal view — search with timeline
arete search "query" --timeline --days 30

# Structured briefing for a task or skill
arete brief --for "task" --skill name --json

# Resolve ambiguous references (people, projects, meetings)
arete resolve "name"

# Person profile with memory
arete people show <slug> --memory

# Open commitments
arete commitments list

# Re-index after file changes
arete index
\`\`\`

Use these services to ground your responses in workspace data rather than guessing.`;
}

function generateMemory(): string {
  return `## Memory

PM decisions are stored in \`.arete/memory/items/decisions.md\`.
Learnings are stored in \`.arete/memory/items/learnings.md\`.

When the user makes a notable decision or learns something worth preserving,
extract it with their approval using the \`extract_decisions_learnings\` pattern.

Claude Code's auto-memory handles agent observations natively — do not duplicate
what Claude Code already captures in its own memory system.`;
}

function generateWorkingPatterns(): string {
  return `## Working Patterns

- **Projects**: Active work lives in \`projects/active/\`. Each project has its own directory.
- **Context**: The \`context/\` directory is the source of truth for business context.
  Read it before making strategic recommendations.
- **Quick capture**: Use \`now/scratchpad.md\` for rapid notes and ideas.
- **People**: Person files in \`people/\` contain relationship context and meeting history.
- **Agent profiles**: Skills may reference agent profiles in \`.agents/profiles/\`.
  When a skill's frontmatter includes \`profile:\`, read the referenced profile
  at \`.agents/profiles/{profile}.md\` and adopt its voice and approach.
- **Templates**: Check \`templates/\` before creating new documents from scratch.`;
}

function generateFooter(config: AreteConfig): string {
  const version = config.version ?? 'unknown';
  const timestamp = new Date().toISOString().split('T')[0];
  return `---

Generated by Arete v${version} on ${timestamp}`;
}
