/**
 * MemoryIndexService — generates `.arete/memory/index.md`, the Obsidian
 * landing page for the wiki layer. Lists topic pages, people, and areas
 * with one-line descriptions and `[[wikilinks]]`.
 *
 * Regenerated only on `arete memory refresh` (not on per-ingest writes).
 * Pure renderer + service wrapper; idempotent write via
 * `StorageAdapter.writeIfChanged`.
 *
 * See plan: dev/work/plans/topic-wiki-memory/plan.md Step 5.
 */

import { join } from 'node:path';
import type { StorageAdapter } from '../storage/adapter.js';
import type { WorkspacePaths } from '../models/workspace.js';
import type { Person } from '../models/entities.js';
import type { AreaParserService } from './area-parser.js';
import type { TopicMemoryService } from './topic-memory.js';
import type { EntityService } from './entity.js';
import { getTopicHeadline, type TopicPage } from '../models/topic-page.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AreaIndexEntry {
  slug: string;
  name: string;
  topicCount: number;
  openItemCount: number;
}

export interface MemoryIndexData {
  topics: TopicPage[];
  people: Person[];
  areas: AreaIndexEntry[];
  /**
   * Errors encountered during data gathering (e.g., corrupt topic page).
   * Surfaced at the bottom of index.md as a diagnostic note —
   * partial-state tolerant per pre-mortem Risk 14.
   */
  errors?: string[];
}

// ---------------------------------------------------------------------------
// Pure renderer
// ---------------------------------------------------------------------------

/**
 * Render MemoryIndexData as markdown. Pure — no I/O, no wall-clock reads.
 * Stable output for equal inputs.
 */
export function renderMemoryIndex(data: MemoryIndexData): string {
  const lines: string[] = [
    '# Memory Index',
    '',
    '> Auto-generated catalog of Areté memory surfaces. Regenerated by `arete memory refresh`.',
    '> Edits here are overwritten on next refresh.',
    '',
  ];

  // ---------- Topics ----------
  if (data.topics.length > 0) {
    const sorted = [...data.topics].sort((a, b) => {
      const aSlug = a.frontmatter.topic_slug;
      const bSlug = b.frontmatter.topic_slug;
      if (aSlug < bSlug) return -1;
      if (aSlug > bSlug) return 1;
      return 0;
    });
    lines.push(`## Topics (${sorted.length})`);
    lines.push('');
    for (const page of sorted) {
      const slug = page.frontmatter.topic_slug;
      const status = page.frontmatter.status;
      const headline = getTopicHeadline(page);
      const date = page.frontmatter.last_refreshed;
      const summary = headline.length > 0 ? ` — ${headline}` : '';
      lines.push(`- [[${slug}]] — ${status}${summary} _(updated: ${date})_`);
    }
    lines.push('');
  }

  // ---------- People ----------
  if (data.people.length > 0) {
    // Already sorted upstream by EntityService.listPeople, but re-sort for safety.
    const sorted = [...data.people].sort((a, b) => {
      if (a.slug < b.slug) return -1;
      if (a.slug > b.slug) return 1;
      return 0;
    });
    lines.push(`## People (${sorted.length})`);
    lines.push('');
    for (const p of sorted) {
      const role = [p.role, p.company, p.team].filter((s) => s !== undefined && s !== null && s !== '').join(', ');
      const rolePart = role.length > 0 ? ` — ${role}` : '';
      lines.push(`- [[${p.slug}]] — ${p.name}${rolePart}`);
    }
    lines.push('');
  }

  // ---------- Areas ----------
  if (data.areas.length > 0) {
    const sorted = [...data.areas].sort((a, b) => {
      if (a.slug < b.slug) return -1;
      if (a.slug > b.slug) return 1;
      return 0;
    });
    lines.push(`## Areas (${sorted.length})`);
    lines.push('');
    for (const a of sorted) {
      const parts: string[] = [];
      if (a.topicCount > 0) parts.push(`${a.topicCount} topic${a.topicCount === 1 ? '' : 's'}`);
      if (a.openItemCount > 0) parts.push(`${a.openItemCount} open`);
      const suffix = parts.length > 0 ? ` — ${parts.join(', ')}` : '';
      lines.push(`- [[${a.slug}]] — ${a.name}${suffix}`);
    }
    lines.push('');
  }

  // ---------- Errors (diagnostic footer) ----------
  if (data.errors !== undefined && data.errors.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push(`<!-- ${data.errors.length} item(s) excluded due to errors; run \`arete topic lint\` -->`);
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

export class MemoryIndexService {
  constructor(
    private readonly storage: StorageAdapter,
    private readonly topicMemory: TopicMemoryService,
    private readonly entity: EntityService,
    private readonly areaParser: AreaParserService,
    /** Optional CommitmentsService dependency for computing per-area open counts. */
    private readonly commitments: { listOpen(opts?: { area?: string }): Promise<unknown[]> },
  ) {}

  /**
   * Gather data from all memory surfaces and render `index.md`. Idempotent:
   * when content byte-equals existing file, no write is performed.
   *
   * Returns the write result for observability:
   *   'unchanged' → no write (content stable)
   *   'updated'   → new content written
   */
  async refreshMemoryIndex(
    workspacePaths: WorkspacePaths,
  ): Promise<'unchanged' | 'updated'> {
    const data = await this.gatherIndexData(workspacePaths);
    const content = renderMemoryIndex(data);
    const outPath = join(workspacePaths.memory, 'index.md');

    if (this.storage.writeIfChanged !== undefined) {
      return this.storage.writeIfChanged(outPath, content);
    }
    const existing = await this.storage.read(outPath);
    if (existing === content) return 'unchanged';
    await this.storage.write(outPath, content);
    return 'updated';
  }

  /**
   * Gather raw data for the index. Exported as a method (not pure function)
   * because each data source requires its own service. Partial-state tolerant
   * — errors from any source surface in `data.errors` without failing the
   * whole gather.
   */
  async gatherIndexData(workspacePaths: WorkspacePaths): Promise<MemoryIndexData> {
    const errors: string[] = [];

    // Topics
    let topics: TopicPage[] = [];
    try {
      const { topics: t, errors: topicErrors } = await this.topicMemory.listAll(workspacePaths);
      topics = t;
      for (const e of topicErrors) errors.push(`topic "${e.path}": ${e.reason}`);
    } catch (err) {
      errors.push(`topic listAll failed: ${err instanceof Error ? err.message : 'unknown'}`);
    }

    // People
    let people: Person[] = [];
    try {
      people = await this.entity.listPeople(workspacePaths);
    } catch (err) {
      errors.push(`listPeople failed: ${err instanceof Error ? err.message : 'unknown'}`);
    }

    // Areas — count topics per area from the topic frontmatter we already loaded;
    // count open items via commitments per area.
    let areas: AreaIndexEntry[] = [];
    try {
      const parsedAreas = await this.areaParser.listAreas();
      const topicsByArea = new Map<string, number>();
      for (const page of topics) {
        const area = page.frontmatter.area;
        if (area === undefined) continue;
        topicsByArea.set(area, (topicsByArea.get(area) ?? 0) + 1);
      }
      areas = await Promise.all(
        parsedAreas.map(async (a) => {
          let openItemCount = 0;
          try {
            const open = await this.commitments.listOpen({ area: a.slug });
            openItemCount = open.length;
          } catch {
            // Per-area commitments read failure: leave as 0; errors aggregated above.
          }
          return {
            slug: a.slug,
            name: a.name,
            topicCount: topicsByArea.get(a.slug) ?? 0,
            openItemCount,
          };
        }),
      );
    } catch (err) {
      errors.push(`listAreas failed: ${err instanceof Error ? err.message : 'unknown'}`);
    }

    return { topics, people, areas, errors: errors.length > 0 ? errors : undefined };
  }
}
