/**
 * Source-summary domain model: schema, pure renderer, pure parser.
 *
 * Source summaries are written under `.arete/memory/summaries/<source-type>/<slug>.md`.
 * One file per primary unit of knowledge ingested (per the absorption
 * principle in `arete-v2-chef-orchestrator/phase-1-wiki-expansion/plan.md`):
 *
 *  - meetings — `.arete/memory/summaries/meetings/<date>-<slug>.md`
 *  - inbox docs — `.arete/memory/summaries/inbox/<doc-id>.md`
 *  - slack threads — `.arete/memory/summaries/slack/<thread-id>.md`
 *
 * Subsidiary inputs (Notion notes pulled as meeting context, agendas, etc.)
 * are absorbed into the parent's summary, not summarized separately.
 *
 * This module is pure: no I/O, no clock reads. Consumers inject any
 * timestamps they need.
 *
 * The model carries TWO body shapes (meeting and inbox/slack) under the
 * same envelope. Phase 1 ships meeting + inbox shapes; slack-thread shape
 * reuses the inbox shape. Section ordering is canonical and load-bearing
 * for renderer idempotency.
 */

import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SourceType = 'meeting' | 'inbox' | 'slack';

/**
 * Frontmatter shape for source summaries. `source_type` discriminates;
 * fields beyond the common core are optional and shape-specific.
 */
export interface SourceSummaryFrontmatter {
  source_path: string;            // workspace-relative path to the primary source file
  source_type: SourceType;
  date: string;                   // YYYY-MM-DD
  area?: string;
  importance?: 'skip' | 'light' | 'standard' | 'heavy';
  topics?: string[];              // slug list
  participants?: string[];        // free-form names (meeting attendees, slack participants)
  extraction_version?: string;    // semver-ish marker so a future schema bump can trigger re-summary
}

/**
 * Section names for meeting summaries. Order is canonical and load-bearing
 * for renderer idempotency.
 *
 * "What happened" carries the post-call-email narrative; "Things mentioned
 * but not actioned" replaces today's `## Could include` body block.
 */
export const MEETING_SECTION_NAMES = [
  'What happened',
  'What was decided',
  "What's next",
  'Open questions',
  'FYI',
  'Things mentioned but not actioned',
] as const;

export type MeetingSectionName = typeof MEETING_SECTION_NAMES[number];

/**
 * Section names for inbox-doc and slack-thread summaries. Source-agnostic
 * shape — same render order is shared for both (slack threads reuse the
 * inbox shape).
 */
export const INBOX_SECTION_NAMES = [
  'Summary',
  'Key points',
  "What's relevant",
  'Followups',
] as const;

export type InboxSectionName = typeof INBOX_SECTION_NAMES[number];

export type MeetingSummarySections = Partial<Record<MeetingSectionName, string>>;
export type InboxSummarySections = Partial<Record<InboxSectionName, string>>;

export interface MeetingSummary {
  frontmatter: SourceSummaryFrontmatter & { source_type: 'meeting' };
  sections: MeetingSummarySections;
}

export interface InboxSummary {
  frontmatter: SourceSummaryFrontmatter & { source_type: 'inbox' | 'slack' };
  sections: InboxSummarySections;
}

export type SourceSummary = MeetingSummary | InboxSummary;

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/**
 * Render a SourceSummary as markdown. Pure; stable output for equal inputs.
 *
 * Output shape:
 *   ---
 *   <YAML frontmatter>
 *   ---
 *
 *   # {Title derived from source_path or topic}
 *
 *   > Auto-generated. Regenerated by `arete meeting apply` /
 *   > `arete inbox add` / slack-digest writer when source changes.
 *
 *   ## <section> ...
 */
export function renderSourceSummary(summary: SourceSummary): string {
  const fm = normalizeFrontmatter(summary.frontmatter);
  const yaml = stringifyYaml(fm, {
    sortMapEntries: false,
    lineWidth: 0,
  }).trimEnd();

  const title = deriveTitle(summary);

  const lines: string[] = [
    '---',
    yaml,
    '---',
    '',
    `# ${title}`,
    '',
    '> Auto-generated summary. Regenerated when the source file changes.',
    '',
  ];

  const sectionNames: readonly string[] =
    summary.frontmatter.source_type === 'meeting'
      ? MEETING_SECTION_NAMES
      : INBOX_SECTION_NAMES;

  for (const name of sectionNames) {
    const body = (summary.sections as Record<string, string | undefined>)[name];
    if (body === undefined) continue;
    const trimmed = body.trim();
    if (trimmed.length === 0) continue;
    lines.push(`## ${name}`);
    lines.push('');
    lines.push(trimmed);
    lines.push('');
  }

  // Collapse trailing blanks to a single newline.
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  lines.push('');
  return lines.join('\n');
}

function deriveTitle(summary: SourceSummary): string {
  const fm = summary.frontmatter;
  const base = fm.source_path.split(/[/\\]/).pop() ?? fm.source_path;
  const stripped = base.replace(/\.md$/i, '');
  // Replace dashes/underscores with spaces, drop leading date prefix
  // (YYYY-MM-DD-) for readability.
  const noDate = stripped.replace(/^\d{4}-\d{2}-\d{2}-/, '');
  return noDate.replace(/[-_]+/g, ' ').replace(/\s+/g, ' ').trim() || stripped;
}

function normalizeFrontmatter(
  fm: SourceSummaryFrontmatter,
): Record<string, unknown> {
  // Preserve insertion order via explicit object construction.
  const out: Record<string, unknown> = {
    source_path: fm.source_path,
    source_type: fm.source_type,
    date: fm.date,
  };
  if (fm.area !== undefined) out.area = fm.area;
  if (fm.importance !== undefined) out.importance = fm.importance;
  if (fm.topics !== undefined && fm.topics.length > 0) {
    out.topics = [...fm.topics];
  }
  if (fm.participants !== undefined && fm.participants.length > 0) {
    out.participants = [...fm.participants];
  }
  if (fm.extraction_version !== undefined) {
    out.extraction_version = fm.extraction_version;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Parsing (round-trip)
// ---------------------------------------------------------------------------

/**
 * Parse a source-summary markdown file into the model shape. Returns
 * `null` if the file is malformed (no frontmatter or invalid source_type).
 *
 * Tolerant: missing optional frontmatter fields are dropped; unknown
 * section headers are ignored; `## ` headers inside fenced code blocks
 * are NOT treated as section starts (same fence-tracking as
 * `parseMemorySections` in services/memory.ts).
 */
export function parseSourceSummary(content: string): SourceSummary | null {
  const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!fmMatch) return null;

  let fmRaw: unknown;
  try {
    fmRaw = parseYaml(fmMatch[1]);
  } catch {
    return null;
  }
  if (fmRaw === null || typeof fmRaw !== 'object' || Array.isArray(fmRaw)) {
    return null;
  }
  const fmRec = fmRaw as Record<string, unknown>;

  const sourcePath = fmRec.source_path;
  const sourceType = fmRec.source_type;
  const date = fmRec.date;
  if (typeof sourcePath !== 'string' || sourcePath.length === 0) return null;
  if (sourceType !== 'meeting' && sourceType !== 'inbox' && sourceType !== 'slack') {
    return null;
  }
  if (typeof date !== 'string' || date.length === 0) return null;

  const fm: SourceSummaryFrontmatter = {
    source_path: sourcePath,
    source_type: sourceType,
    date,
  };
  if (typeof fmRec.area === 'string') fm.area = fmRec.area;
  if (
    fmRec.importance === 'skip' ||
    fmRec.importance === 'light' ||
    fmRec.importance === 'standard' ||
    fmRec.importance === 'heavy'
  ) {
    fm.importance = fmRec.importance;
  }
  if (Array.isArray(fmRec.topics)) {
    const topics = fmRec.topics
      .filter((t): t is string => typeof t === 'string' && t.trim().length > 0);
    if (topics.length > 0) fm.topics = topics;
  }
  if (Array.isArray(fmRec.participants)) {
    const participants = fmRec.participants
      .filter((p): p is string => typeof p === 'string' && p.trim().length > 0);
    if (participants.length > 0) fm.participants = participants;
  }
  if (typeof fmRec.extraction_version === 'string') {
    fm.extraction_version = fmRec.extraction_version;
  }

  // Parse body sections.
  const body = fmMatch[2];
  const sectionMap = parseSummarySections(
    body,
    sourceType === 'meeting' ? MEETING_SECTION_NAMES : INBOX_SECTION_NAMES,
  );

  if (sourceType === 'meeting') {
    return {
      frontmatter: fm as SourceSummaryFrontmatter & { source_type: 'meeting' },
      sections: sectionMap as MeetingSummarySections,
    };
  }
  return {
    frontmatter: fm as SourceSummaryFrontmatter & { source_type: 'inbox' | 'slack' },
    sections: sectionMap as InboxSummarySections,
  };
}

/**
 * Parse `## Section` blocks out of summary body content.
 * Fence-aware (headers inside ``` blocks don't count). Only recognized
 * section names are kept; unknown headers are discarded.
 */
function parseSummarySections(
  body: string,
  recognized: readonly string[],
): Partial<Record<string, string>> {
  const allowed = new Set(recognized);
  const lines = body.split(/\r?\n/);
  const sections: Record<string, string[]> = {};
  let currentName: string | null = null;
  let inFence = false;

  for (const line of lines) {
    if (/^```/.test(line)) {
      inFence = !inFence;
      if (currentName !== null) sections[currentName].push(line);
      continue;
    }
    if (!inFence) {
      const m = line.match(/^##\s+(.+?)\s*$/);
      if (m) {
        const name = m[1].trim();
        if (allowed.has(name)) {
          currentName = name;
          if (!sections[currentName]) sections[currentName] = [];
        } else {
          currentName = null; // unrecognized; drop content until next recognized header
        }
        continue;
      }
    }
    if (currentName !== null) {
      sections[currentName].push(line);
    }
  }

  const out: Partial<Record<string, string>> = {};
  for (const [name, lines] of Object.entries(sections)) {
    const trimmed = lines.join('\n').trim();
    if (trimmed.length > 0) out[name] = trimmed;
  }
  return out;
}
