/**
 * Topic page domain model: schema, pure renderer, pure parser.
 *
 * Topic pages are the encyclopedic L3 substrate — one markdown file
 * per topic at `.arete/memory/topics/{slug}.md`. Fully system-owned,
 * regenerated wholesale by `TopicMemoryService` (no sentinels; no
 * user-writable preamble).
 *
 * This module is pure: no I/O, no clock reads. Consumers inject any
 * timestamps they need.
 *
 * See plan: dev/work/plans/topic-wiki-memory/plan.md Step 1.
 */

import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

export type TopicStatus =
  | 'new'
  | 'active'
  | 'stable'
  | 'blocked'
  | 'stale'
  | 'archived';

export interface TopicSourceRef {
  path: string;      // relative to workspace root (e.g., "resources/meetings/2026-04-16-foo.md")
  date: string;      // YYYY-MM-DD
  hash: string;      // first 8 chars of SHA-256 of the source file content at integration time
}

export interface TopicEntities {
  people?: string[];          // slugs
  related_topics?: string[];  // slugs
}

export interface TopicPageFrontmatter {
  topic_slug: string;
  area?: string;
  status: TopicStatus;
  aliases?: string[];
  entities?: TopicEntities;
  first_seen: string;         // YYYY-MM-DD
  last_refreshed: string;     // YYYY-MM-DD
  sources_integrated: TopicSourceRef[];
}

/**
 * Section names, rendered in this canonical order.
 * Order is load-bearing for idempotency — changing it rewrites every
 * topic page.
 */
export const SECTION_NAMES = [
  'Current state',
  'Why/background',
  'Scope and behavior',
  'Rollout/timeline',
  'Open questions',
  'Known gaps',
  'Relationships',
  'Source trail',
  'Change log',
] as const;

export type SectionName = typeof SECTION_NAMES[number];

export type TopicSections = Partial<Record<SectionName, string>>;

export interface TopicPage {
  frontmatter: TopicPageFrontmatter;
  sections: TopicSections;
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/**
 * Render a TopicPage as markdown. Pure; stable output for equal inputs.
 *
 * Output shape:
 *   ---
 *   <YAML frontmatter>
 *   ---
 *
 *   # {topic_slug titleized}
 *
 *   > Auto-generated. Do not edit — regenerated by `arete topic refresh`.
 *
 *   ## Current state
 *   ...
 *
 *   ## Why/background
 *   ...
 *
 *   (sections in SECTION_NAMES order; omitted sections skipped)
 */
export function renderTopicPage(page: TopicPage): string {
  const fm = normalizeFrontmatter(page.frontmatter);
  const yaml = stringifyYaml(fm, {
    // Stable ordering for idempotency; yaml library preserves insertion order.
    sortMapEntries: false,
    lineWidth: 0,
  }).trimEnd();

  const title = titleize(page.frontmatter.topic_slug);

  const lines: string[] = [
    '---',
    yaml,
    '---',
    '',
    `# ${title}`,
    '',
    '> Auto-generated. Do not edit — regenerated by `arete topic refresh`.',
    '',
  ];

  for (const name of SECTION_NAMES) {
    const body = page.sections[name];
    if (body === undefined) continue;
    const trimmed = body.trim();
    if (trimmed.length === 0) continue;
    lines.push(`## ${name}`);
    lines.push('');
    lines.push(trimmed);
    lines.push('');
  }

  // Single trailing newline; no double newlines at EOF.
  return lines.join('\n').replace(/\n+$/, '\n');
}

/**
 * Normalize frontmatter for stable serialization.
 * - Fields appear in a canonical order
 * - Optional fields with empty arrays are omitted (not rendered as `[]`)
 * - Slugs in aliases/people/related_topics are sorted ASCII (deterministic)
 * - sources_integrated retains insertion order (chronological by write-time)
 */
function normalizeFrontmatter(fm: TopicPageFrontmatter): Record<string, unknown> {
  const out: Record<string, unknown> = {
    topic_slug: fm.topic_slug,
  };

  if (fm.area !== undefined) out.area = fm.area;
  out.status = fm.status;

  if (fm.aliases && fm.aliases.length > 0) {
    out.aliases = [...fm.aliases].sort();
  }

  const entities = fm.entities;
  if (entities && hasEntityContent(entities)) {
    const entOut: Record<string, unknown> = {};
    if (entities.people && entities.people.length > 0) {
      entOut.people = [...entities.people].sort();
    }
    if (entities.related_topics && entities.related_topics.length > 0) {
      entOut.related_topics = [...entities.related_topics].sort();
    }
    out.entities = entOut;
  }

  out.first_seen = fm.first_seen;
  out.last_refreshed = fm.last_refreshed;
  out.sources_integrated = fm.sources_integrated.map((s) => ({
    path: s.path,
    date: s.date,
    hash: s.hash,
  }));

  return out;
}

function hasEntityContent(e: TopicEntities): boolean {
  return (
    (e.people !== undefined && e.people.length > 0) ||
    (e.related_topics !== undefined && e.related_topics.length > 0)
  );
}

function titleize(slug: string): string {
  return slug
    .split('-')
    .filter((w) => w.length > 0)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---\n?/;
const SECTION_HEADING_RE = /^##\s+(.+?)\s*$/;

/**
 * Parse a rendered topic page back into a TopicPage.
 * Returns null if the file is not a valid topic page (missing frontmatter
 * or malformed).
 *
 * Round-trip invariant: `renderTopicPage(parseTopicPage(x)!) === x`
 * holds for any `x` produced by `renderTopicPage`.
 */
export function parseTopicPage(content: string): TopicPage | null {
  const match = FRONTMATTER_RE.exec(content);
  if (!match) return null;

  let fmRaw: unknown;
  try {
    fmRaw = parseYaml(match[1]);
  } catch {
    return null;
  }

  if (fmRaw === null || typeof fmRaw !== 'object' || Array.isArray(fmRaw)) {
    return null;
  }

  const fm = fmRaw as Record<string, unknown>;

  const topic_slug = asString(fm.topic_slug);
  if (topic_slug === undefined) return null;

  const status = asStatus(fm.status);
  if (status === undefined) return null;

  const first_seen = asString(fm.first_seen);
  const last_refreshed = asString(fm.last_refreshed);
  if (first_seen === undefined || last_refreshed === undefined) return null;

  const sources_integrated = asSourceRefs(fm.sources_integrated);
  if (sources_integrated === undefined) return null;

  const frontmatter: TopicPageFrontmatter = {
    topic_slug,
    status,
    first_seen,
    last_refreshed,
    sources_integrated,
  };

  const area = asString(fm.area);
  if (area !== undefined) frontmatter.area = area;

  const aliases = asStringArray(fm.aliases);
  if (aliases !== undefined) frontmatter.aliases = aliases;

  const entities = asEntities(fm.entities);
  if (entities !== undefined) frontmatter.entities = entities;

  const body = content.slice(match[0].length);
  const sections = parseSections(body);

  return { frontmatter, sections };
}

function parseSections(body: string): TopicSections {
  const sections: TopicSections = {};
  const lines = body.split('\n');

  let currentName: SectionName | null = null;
  let currentLines: string[] = [];

  const flush = () => {
    if (currentName === null) return;
    const text = currentLines.join('\n').trim();
    if (text.length > 0) {
      sections[currentName] = text;
    }
    currentLines = [];
  };

  for (const line of lines) {
    const heading = SECTION_HEADING_RE.exec(line);
    if (heading) {
      flush();
      const name = heading[1];
      if ((SECTION_NAMES as readonly string[]).includes(name)) {
        currentName = name as SectionName;
      } else {
        currentName = null; // unknown section — skip body until next heading
      }
      continue;
    }
    if (currentName !== null) {
      currentLines.push(line);
    }
  }

  flush();
  return sections;
}

// ---------------------------------------------------------------------------
// Parse helpers — defensive narrowing from unknown YAML output
// ---------------------------------------------------------------------------

function asString(v: unknown): string | undefined {
  return typeof v === 'string' ? v : undefined;
}

function asStringArray(v: unknown): string[] | undefined {
  if (!Array.isArray(v)) return undefined;
  const out: string[] = [];
  for (const item of v) {
    if (typeof item === 'string') out.push(item);
  }
  return out.length > 0 ? out : undefined;
}

const VALID_STATUSES: readonly TopicStatus[] = [
  'new',
  'active',
  'stable',
  'blocked',
  'stale',
  'archived',
];

function asStatus(v: unknown): TopicStatus | undefined {
  if (typeof v !== 'string') return undefined;
  return (VALID_STATUSES as readonly string[]).includes(v)
    ? (v as TopicStatus)
    : undefined;
}

function asSourceRefs(v: unknown): TopicSourceRef[] | undefined {
  if (!Array.isArray(v)) return undefined;
  const out: TopicSourceRef[] = [];
  for (const item of v) {
    if (item === null || typeof item !== 'object' || Array.isArray(item)) continue;
    const rec = item as Record<string, unknown>;
    const path = asString(rec.path);
    const date = asString(rec.date);
    const hash = asString(rec.hash);
    if (path === undefined || date === undefined || hash === undefined) continue;
    out.push({ path, date, hash });
  }
  return out;
}

// ---------------------------------------------------------------------------
// Shared helpers (used by AreaMemoryService, TopicMemoryService, CLAUDE.md
// generator, and skill context-bundle assembly). Factored here so the same
// truncation rules apply everywhere.
// ---------------------------------------------------------------------------

/**
 * First non-empty line of `Current state`, truncated to ~120 chars with an
 * ellipsis. Used for:
 *   - Area file Topics index line
 *   - CLAUDE.md Active Topics block
 *   - `arete topic list` output
 * Returns empty string if Current state is missing/empty.
 */
export function getTopicHeadline(page: TopicPage, maxChars = 120): string {
  const current = page.sections['Current state'];
  if (current === undefined) return '';
  const firstLine = current.split('\n').find((l) => l.trim().length > 0);
  if (firstLine === undefined) return '';
  const trimmed = firstLine.trim();
  if (trimmed.length <= maxChars) return trimmed;
  // Truncate on a word boundary if possible.
  const cutoff = trimmed.slice(0, maxChars);
  const lastSpace = cutoff.lastIndexOf(' ');
  const head = lastSpace > maxChars * 0.7 ? cutoff.slice(0, lastSpace) : cutoff;
  return head.trimEnd() + '…';
}

/**
 * Priority order for section inclusion when budget is tight.
 * Higher priority sections are included first.
 *
 * `Source trail` and `Change log` are deliberately excluded: they carry
 * provenance/audit data (low information density for skill context
 * injection) and `topic_page_retrieval` callers want synthesized
 * narrative, not a list of meeting references. To include those, callers
 * read the raw topic page directly via `renderTopicPage`.
 */
const SECTION_PRIORITY: SectionName[] = [
  'Current state',
  'Open questions',
  'Scope and behavior',
  'Why/background',
  'Known gaps',
  'Relationships',
  'Rollout/timeline',
];

/**
 * Select sections to fit within a word budget, in priority order.
 * Always includes `Current state` first (even if it alone exceeds budget).
 * Subsequent sections are included only if the running total stays within
 * budget. Returns rendered markdown (just the selected sections, no
 * frontmatter or title).
 *
 * Used by `topic_page_retrieval` pattern to inject topic content into skill
 * context without blowing the 1000-word memory budget in
 * `context_bundle_assembly`.
 */
export function selectSectionsForBudget(
  page: TopicPage,
  budgetWords: number,
): string {
  const selected: string[] = [];
  let wordCount = 0;
  let first = true;

  for (const name of SECTION_PRIORITY) {
    const body = page.sections[name];
    if (body === undefined) continue;
    const trimmed = body.trim();
    if (trimmed.length === 0) continue;

    const sectionWords = countWords(trimmed);

    if (first) {
      // Always include Current state / highest-priority section, even if
      // it alone blows the budget — it's the most valuable signal.
      selected.push(`## ${name}\n\n${trimmed}`);
      wordCount += sectionWords;
      first = false;
      continue;
    }

    if (wordCount + sectionWords > budgetWords) break;
    selected.push(`## ${name}\n\n${trimmed}`);
    wordCount += sectionWords;
  }

  return selected.join('\n\n');
}

function countWords(text: string): number {
  const matches = text.match(/\S+/g);
  return matches === null ? 0 : matches.length;
}

function asEntities(v: unknown): TopicEntities | undefined {
  if (v === null || typeof v !== 'object' || Array.isArray(v)) return undefined;
  const rec = v as Record<string, unknown>;
  const entities: TopicEntities = {};
  const people = asStringArray(rec.people);
  if (people !== undefined) entities.people = people;
  const related = asStringArray(rec.related_topics);
  if (related !== undefined) entities.related_topics = related;
  return hasEntityContent(entities) ? entities : undefined;
}
