#!/usr/bin/env tsx
/**
 * Build AGENTS.md from modular source files in .agents/sources/
 * 
 * Usage:
 *   npx tsx scripts/build-agents.ts dev   # Generate AGENTS.md for BUILD
 *   npx tsx scripts/build-agents.ts prod  # Generate dist/AGENTS.md for GUIDE
 * 
 * Targets:
 *   dev  - BUILD version (shared + builder) → AGENTS.md
 *   prod - GUIDE version (shared + guide) → dist/AGENTS.md
 */

import { readFile, writeFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { existsSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');
const sourcesDir = join(root, '.agents', 'sources');

type Target = 'dev' | 'prod';

interface BuildConfig {
  target: Target;
  sourceFiles: string[];
  outputPath: string;
}

/**
 * Get build configuration based on target
 */
function getConfig(target: Target): BuildConfig {
  const sharedFiles = [
    'shared/vision.md',
    'shared/workspace-structure.md',
    'shared/cli-commands.md',
  ];

  const builderFiles = [
    'builder/skills-index.md',
    'builder/rules-index.md',
    'builder/conventions.md',
    'builder/memory.md',
  ];

  const guideFiles = [
    'guide/skills-index.md',
    'guide/tools-index.md',
    'guide/intelligence.md',
    'guide/workflows.md',
  ];

  if (target === 'dev') {
    return {
      target,
      sourceFiles: [...sharedFiles, ...builderFiles],
      outputPath: join(root, 'AGENTS.md'),
    };
  } else {
    return {
      target,
      sourceFiles: [...sharedFiles, ...guideFiles],
      outputPath: join(root, 'dist', 'AGENTS.md'),
    };
  }
}

/**
 * Read and concatenate source files
 */
async function readSourceFiles(sourceFiles: string[]): Promise<string> {
  const contents: string[] = [];

  for (const file of sourceFiles) {
    const filePath = join(sourcesDir, file);
    
    if (!existsSync(filePath)) {
      console.warn(`Warning: Source file not found: ${file}`);
      continue;
    }

    try {
      const content = await readFile(filePath, 'utf-8');
      contents.push(content.trim());
    } catch (error) {
      console.error(`Error reading ${file}:`, error);
      throw error;
    }
  }

  return contents.join('\n\n');
}

/**
 * Generate header with metadata
 */
function generateHeader(sourceFiles: string[]): string {
  const timestamp = new Date().toISOString();
  const fileList = sourceFiles.map(f => `  - ${f}`).join('\n');

  return `# Areté - Product Builder's Operating System

<!-- Generated by build-agents.ts at ${timestamp} -->
<!-- DO NOT EDIT MANUALLY - Edit source files in .agents/sources/ -->
<!-- Source files:
${fileList}
-->

---
`;
}

/**
 * Build AGENTS.md for the specified target
 */
async function buildAgents(target: Target): Promise<void> {
  console.log(`Building AGENTS.md for target: ${target}`);

  // Get configuration
  const config = getConfig(target);
  console.log(`Output: ${config.outputPath}`);
  console.log(`Source files: ${config.sourceFiles.length}`);

  // Ensure output directory exists
  const outputDir = dirname(config.outputPath);
  if (!existsSync(outputDir)) {
    await mkdir(outputDir, { recursive: true });
  }

  // Read source files
  const content = await readSourceFiles(config.sourceFiles);

  // Generate header
  const header = generateHeader(config.sourceFiles);

  // Combine and write
  const output = header + content;
  await writeFile(config.outputPath, output, 'utf-8');

  // Report size
  const sizeKB = (output.length / 1024).toFixed(2);
  console.log(`✓ Generated ${config.outputPath} (${sizeKB} KB)`);

  // Warn if too large
  if (output.length > 10240) {
    console.warn(`⚠ Warning: Output size (${sizeKB} KB) exceeds 10 KB threshold`);
  }
}

/**
 * Main entry point
 */
async function main(): Promise<void> {
  const targetArg = process.argv[2] as Target | undefined;
  const target: Target = targetArg === 'prod' ? 'prod' : 'dev';

  if (targetArg && targetArg !== 'dev' && targetArg !== 'prod') {
    console.error(`Invalid target: ${targetArg}`);
    console.error('Usage: npx ts-node scripts/build-agents.ts [dev|prod]');
    process.exit(1);
  }

  try {
    await buildAgents(target);
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

main();
