/**
 * Claude Code IDE Adapter
 *
 * Adapters may use fs directly (infrastructure).
 */

import { existsSync } from 'fs';
import { join } from 'path';
import type { IDEAdapter, CanonicalRule, IDETarget } from './ide-adapter.js';
import type { AreteConfig } from '../models/workspace.js';
import { readPrebuiltAgentsMd, generateMinimalAgentsMd } from './read-agents-md.js';

/**
 * Transform Cursor-specific paths to Claude-specific paths.
 * dist/AGENTS.md uses .cursor/ paths; Claude needs .claude/.
 */
function transformPathsForClaude(content: string): string {
  return content
    .replace(/\.cursor\/skills\//g, '.agents/skills/')
    .replace(/\.cursor\//g, '.claude/')
    .replace(/\.mdc\b/g, '.md');
}

export class ClaudeAdapter implements IDEAdapter {
  readonly target: IDETarget = 'claude';
  readonly configDirName = '.claude';
  readonly ruleExtension = '.md';

  getIDEDirs(): string[] {
    return [
      '.claude',
      '.claude/rules',
      '.claude/tools',
      '.claude/integrations',
      '.claude/integrations/configs',
    ];
  }

  rulesDir(): string {
    return '.claude/rules';
  }

  toolsDir(): string {
    return '.claude/tools';
  }

  integrationsDir(): string {
    return '.claude/integrations';
  }

  formatRule(rule: CanonicalRule, _config: AreteConfig): string {
    const frontmatter: Record<string, unknown> = {
      description: rule.description,
    };
    if (rule.alwaysApply !== true && rule.globs && rule.globs.length > 0) {
      frontmatter.globs = rule.globs;
    }
    const yamlLines = ['---'];
    for (const [key, value] of Object.entries(frontmatter)) {
      if (Array.isArray(value)) {
        yamlLines.push(`${key}:`);
        for (const item of value) {
          yamlLines.push(`  - "${item}"`);
        }
      } else if (typeof value === 'boolean') {
        yamlLines.push(`${key}: ${value}`);
      } else {
        yamlLines.push(`${key}: ${value}`);
      }
    }
    yamlLines.push('---');
    return `${yamlLines.join('\n')}\n\n${rule.content}`;
  }

  transformRuleContent(content: string): string {
    return content
      .replace(/\.cursor\/skills\//g, '.agents/skills/')
      .replace(/\.cursor\//g, '.claude/')
      .replace(/\.mdc\b/g, '.md');
  }

  generateRootFiles(
    config: AreteConfig,
    _workspaceRoot: string,
    _sourceRulesDir?: string
  ): Record<string, string> {
    const timestamp = new Date().toISOString();
    const version = config.version || '1.0.0';

    // Try to read pre-built comprehensive AGENTS.md from dist/
    let claudeMd = readPrebuiltAgentsMd();

    if (claudeMd) {
      // Transform .cursor/ paths to .claude/ paths
      claudeMd = transformPathsForClaude(claudeMd);
    } else {
      // Fall back to minimal version if pre-built not available
      claudeMd = generateMinimalAgentsMd();
    }

    // Append version footer
    const versionFooter = `
---

## Version

Generated by Areté v${version} on ${timestamp}
`;
    claudeMd = claudeMd.trimEnd() + '\n' + versionFooter;

    return { 'CLAUDE.md': claudeMd };
  }

  detectInWorkspace(workspaceRoot: string): boolean {
    return existsSync(join(workspaceRoot, '.claude'));
  }
}
