/**
 * Claude Code IDE Adapter
 *
 * Adapters may use fs directly (infrastructure).
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import type { IDEAdapter, CanonicalRule, IDETarget } from './ide-adapter.js';
import type { AreteConfig } from '../models/workspace.js';

export class ClaudeAdapter implements IDEAdapter {
  readonly target: IDETarget = 'claude';
  readonly configDirName = '.claude';
  readonly ruleExtension = '.md';

  getIDEDirs(): string[] {
    return [
      '.claude',
      '.claude/rules',
      '.claude/tools',
      '.claude/integrations',
      '.claude/integrations/configs',
    ];
  }

  rulesDir(): string {
    return '.claude/rules';
  }

  toolsDir(): string {
    return '.claude/tools';
  }

  integrationsDir(): string {
    return '.claude/integrations';
  }

  formatRule(rule: CanonicalRule, _config: AreteConfig): string {
    const frontmatter: Record<string, unknown> = {
      description: rule.description,
    };
    if (rule.alwaysApply !== true && rule.globs && rule.globs.length > 0) {
      frontmatter.globs = rule.globs;
    }
    const yamlLines = ['---'];
    for (const [key, value] of Object.entries(frontmatter)) {
      if (Array.isArray(value)) {
        yamlLines.push(`${key}:`);
        for (const item of value) {
          yamlLines.push(`  - "${item}"`);
        }
      } else if (typeof value === 'boolean') {
        yamlLines.push(`${key}: ${value}`);
      } else {
        yamlLines.push(`${key}: ${value}`);
      }
    }
    yamlLines.push('---');
    return `${yamlLines.join('\n')}\n\n${rule.content}`;
  }

  transformRuleContent(content: string): string {
    return content
      .replace(/\.cursor\/skills\//g, '.agents/skills/')
      .replace(/\.cursor\//g, '.claude/')
      .replace(/\.mdc\b/g, '.md');
  }

  generateRootFiles(
    config: AreteConfig,
    _workspaceRoot: string,
    sourceRulesDir?: string
  ): Record<string, string> {
    const timestamp = new Date().toISOString();
    const version = config.version || '1.0.0';
    let routingContent = `# 🛑 STOP - READ THIS FIRST

Before responding to ANY user request in this Areté workspace:
Use \`arete skill route "<message>"\` to route to the right skill.
`;
    if (sourceRulesDir) {
      const routingPath = join(sourceRulesDir, 'routing-mandatory.mdc');
      if (existsSync(routingPath)) {
        try {
          const fullContent = readFileSync(routingPath, 'utf-8');
          const contentWithoutFrontmatter = fullContent.replace(
            /^---[\s\S]*?---\n\n/,
            ''
          );
          routingContent = contentWithoutFrontmatter.trim();
        } catch {
          // Use fallback
        }
      }
    }
    const claudeMd = `# Areté - Product Builder's Operating System

${routingContent}

## Workspace Structure

\`\`\`
product-workspace/
├── now/               # Current focus
├── goals/             # Strategy and goals
├── context/           # Business context
├── resources/meetings/ # Meeting notes
├── projects/          # Active and archived projects
├── people/            # People
└── .arete/memory/     # Decisions, learnings
\`\`\`

## Version

Generated by Areté v${version} on ${timestamp}
`;
    return { 'CLAUDE.md': claudeMd };
  }

  detectInWorkspace(workspaceRoot: string): boolean {
    return existsSync(join(workspaceRoot, '.claude'));
  }
}
