/**
 * Cursor IDE Adapter
 *
 * Adapters may use fs directly (infrastructure).
 */

import { existsSync } from 'fs';
import { join } from 'path';
import type { IDEAdapter, CanonicalRule, IDETarget } from './ide-adapter.js';
import type { AreteConfig } from '../models/workspace.js';
import { readPrebuiltAgentsMd, generateMinimalAgentsMd } from './read-agents-md.js';

export class CursorAdapter implements IDEAdapter {
  readonly target: IDETarget = 'cursor';
  readonly configDirName = '.cursor';
  readonly ruleExtension = '.mdc';

  getIDEDirs(): string[] {
    return [
      '.cursor',
      '.cursor/rules',
      '.cursor/tools',
      '.cursor/integrations',
      '.cursor/integrations/configs',
    ];
  }

  rulesDir(): string {
    return '.cursor/rules';
  }

  toolsDir(): string {
    return '.cursor/tools';
  }

  integrationsDir(): string {
    return '.cursor/integrations';
  }

  formatRule(rule: CanonicalRule, _config: AreteConfig): string {
    const frontmatter: Record<string, unknown> = {
      description: rule.description,
    };
    if (rule.globs && rule.globs.length > 0) {
      frontmatter.globs = rule.globs;
    }
    if (rule.alwaysApply === true) {
      frontmatter.alwaysApply = true;
    }
    const yamlLines = ['---'];
    for (const [key, value] of Object.entries(frontmatter)) {
      if (Array.isArray(value)) {
        yamlLines.push(`${key}: ${JSON.stringify(value)}`);
      } else if (typeof value === 'boolean') {
        yamlLines.push(`${key}: ${value}`);
      } else {
        yamlLines.push(`${key}: ${value}`);
      }
    }
    yamlLines.push('---');
    return `${yamlLines.join('\n')}\n\n${rule.content}`;
  }

  transformRuleContent(content: string): string {
    return content;
  }

  generateRootFiles(
    config: AreteConfig,
    _workspaceRoot: string,
    _sourceRulesDir?: string
  ): Record<string, string> {
    const timestamp = new Date().toISOString();
    const version = config.version || '1.0.0';

    // Try to read pre-built comprehensive AGENTS.md from dist/
    let agentsMd = readPrebuiltAgentsMd();

    if (!agentsMd) {
      // Fall back to minimal version if pre-built not available
      agentsMd = generateMinimalAgentsMd();
    }

    // Append version footer
    const versionFooter = `
---

## Version

Generated by Areté v${version} on ${timestamp}
`;
    agentsMd = agentsMd.trimEnd() + '\n' + versionFooter;

    return { 'AGENTS.md': agentsMd };
  }

  detectInWorkspace(workspaceRoot: string): boolean {
    return existsSync(join(workspaceRoot, '.cursor'));
  }
}
